export const actionsTypeTopic = {
	FETCH_SUCCESS_TOPICS: "FETCH_SUCCESS_TOPICS",
	FETCH_ERROR_TOPICS: "FETCH_ERROR_TOPICS",

	FETCH_SUCCESS_TOPICS_SORT_TOP: "FETCH_SUCCESS_TOPICS_SORT_TOP",
	FETCH_SUCCESS_TOPICS_SORT_LATEST: "FETCH_SUCCESS_TOPICS_SORT_LATEST",
	FETCH_SUCCESS_TOPICS_SORT_FAVORITE: "FETCH_SUCCESS_TOPICS_SORT_FAVORITE",
};
