// #redux step5

export const actionsTypeGeneral = {
	SET_SPINNER: "SET_SPINNER",
	SET_SNACKBAR: "SET_SNACKBAR",
	SET_USER_INFO: "SET_USER_INFO",
	SET_OPEN_GAME_TYPES: "SET_OPEN_GAME_TYPES",
	TOGGLE_NOTIF_DRAWER: "TOGGLE_NOTIF_DRAWER",
	GET_CATEGORIES_LIST: "GET_CATEGORIES_LIST",
	SET_MODALS: "SET_MODALS", // #modalRedux step1
};
