export const notifActionTypes = {
	FETCH_SUCCESS: "FETCH_NOTIF_SUCCESS",
	FETCH_ERROR: "FETCH_NOTIF_ERROR",
	FETCH_LOADING: "FETCH_NOTIF_LOADING",
	DELETE_NOTIF: "REJECT_REQUEST",
	ACCEPT_REQUEST_NOTIF: "ACCEPT_REQUEST_NOTIF",
};
