export const actionsTypeUser = {
	FETCH_SUCCESS_USER: "FETCH_SUCCESS_USER",
	FETCH_ERROR_USER: "FETCH_ERROR_USER",
	FETCH_LOADING_USER: "FETCH_LOADING_USER",
	UPDATE_AVATAR: "UPDATE_AVATAR",
	UPDATE_USERNAME: "UPDATE_USERNAME",
	UPDATE_LANGUAGE: "UPDATE_LANGUAGE",
};
